language: python
python: 3.5

install:
  - pip3 install pytest-cov pycodestyle codecov

script:
  # This line is required if using a branch of constellation:
  - pip3 install git+https://github.com/reside-ic/constellation@reside-83#egg=constellation
  - pip3 install -r requirements.txt
  - pytest --cov=src
  - pycodestyle .

after_success:
  - codecov

services:
  - docker
