#!/usr/bin/env bash

## Backup all volumes of data used by Naomi, namely:
## db data, redis data, uploaded files, prerun files and results
set -e

SCRIPT_DIR="$(
    cd -- "$(dirname "$0")" >/dev/null 2>&1
    pwd -P
)"
NOW=$(date +'%Y_%d_%m-%H_%M_%S')
BACKUP_PATH="$SCRIPT_DIR/$NOW.tar.gz"
BACKUP_WORKING_DIR="$SCRIPT_DIR/working"
mkdir $BACKUP_WORKING_DIR

clean_up() {
    echo "Backup failed, cleaning up working dir"
    rm -rf $BACKUP_WORKING_DIR
    exit 1
}
trap clean_up ERR

docker exec hint_db pg_dump -U postgres hint >$BACKUP_WORKING_DIR/db_dump.sql
docker run --rm --volumes-from hint_redis -v $BACKUP_WORKING_DIR:/backup busybox tar -czf /backup/redis_backup.tar.gz /data
docker run --rm --volumes-from hint_hintr -v $BACKUP_WORKING_DIR:/backup busybox tar -czf /backup/prerun_backup.tar.gz /prerun
docker run --rm --volumes-from hint_hintr -v $BACKUP_WORKING_DIR:/backup busybox tar -czf /backup/results_backup.tar.gz /results
docker run --rm --volumes-from hint_hintr -v $BACKUP_WORKING_DIR:/backup busybox tar -czf /backup/uploads_backup.tar.gz /uploads

tar -czf $BACKUP_PATH $BACKUP_WORKING_DIR
echo "Backup complete, saved at $BACKUP_PATH"
rm -rf $BACKUP_WORKING_DIR
