#!/usr/bin/env bash

## Restore from a backup
set -eE

volumes=("hint_db_data" "hint_redis_data" "hint_prerun" "hint_results" "hint_uploads" "hint_config")

assert_file_exists $1
RESTORE_DIR="$(
    cd "$(dirname "$1")"
    pwd
)"
RESTORE_PATH=$RESTORE_DIR/$(basename "$1")
RESTORE_WORKING_DIR=$RESTORE_DIR/working
mkdir $RESTORE_WORKING_DIR
clean_up() {
    echo "Restore failed, cleaning up working dir"
    rm -rf $RESTORE_WORKING_DIR
    docker stop restore_pg || true
    docker rm helper || true
    exit 1
}
trap clean_up ERR

array_contains() {
    local seeking=$1
    shift
    local in=1
    for element; do
        if [[ $element == "$seeking" ]]; then
            in=0
            break
        fi
    done
    return $in
}

assert_file_exists() {
    if !([ ! -z "$1" ] && [ -f "$1" ]); then
        echo "Backup archive $1 does not exist"
        echo "Usage: restore <backup_file>"
        exit 1
    fi
}

assert_all_data_exists() {
    if !([ ! -z "$1" ] && [ -d "$1" ] && [ -f "$1/db_dump.sql" ] && [ -f "$1/redis_backup.tar" ] &&
        [ -f "$1/prerun_backup.tar" ] && [ -f "$1/results_backup.tar" ] && [ -f "$1/uploads_backup.tar" ]); then
        echo "Backup archive $1 is incomplete"
        echo "Usage: restore <backup_file>"
        exit 1
    fi
}

create_volumes() {
    existing_volumes=($(docker volume ls --format '{{.Name}}'))
    for volume in ${volumes[@]}; do
        if array_contains "$volume" "${existing_volumes[@]}"; then
            echo "Volume '${volume}' already exists, remove volume before running restore"
            exit 1
        fi
    done
    for volume in ${volumes[@]}; do
        echo "Creating volume ${volume}"
        docker volume create ${volume}
    done
}

wait_for_postgres() {
    echo "waiting 10 seconds for postgres"
    start_ts=$(date +%s)
    for i in $(seq 10); do
        # Using pg_ready as:
        #
        #   pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
        #
        # seems heaps nicer but does not actually work properly
        # because it pulls us up to soon.
        docker exec -i restore_pg psql -U postgres -d postgres -c "select 1;" >/dev/null 2>&1
        result=$?
        if [[ $result -eq 0 ]]; then
            end_ts=$(date +%s)
            echo "postgres is available after $((end_ts - start_ts)) seconds"
            break
        fi
        sleep 1
        echo "...still waiting"
    done
    if [[ $result -ne 0 ]]; then
        echo "Postgres did not become available in time"
        clean_up
    fi
}

restore() {
    create_volumes
    docker run --rm -d -v hint_db_data:/pgdata -e POSTGRES_PASSWORD=password -e PGDATA=/pgdata --name restore_pg postgres:10.3
    wait_for_postgres
    docker exec -i restore_pg psql -U postgres postgres <$1/db_dump.sql >/dev/null
    docker stop restore_pg
    docker run --rm -v hint_redis_data:/data -v $1:/backup busybox tar -xf /backup/redis_backup.tar -C /data
    docker run --rm -v hint_prerun:/data -v $1:/backup busybox tar -xf /backup/prerun_backup.tar -C /data
    docker run --rm -v hint_results:/data -v $1:/backup busybox tar -xf /backup/results_backup.tar -C /data
    docker run --rm -v hint_uploads:/data -v $1:/backup busybox tar -xf /backup/uploads_backup.tar -C /data
}

restore_key() {
    VAULT_PATH=$(cat $RESTORE_WORKING_DIR/cipher_path)
    echo "Restoring keys from vault path '$VAULT_PATH'"
    VAULT_ADDR="https://vault.dide.ic.ac.uk:8200"
    vault login -address=$VAULT_ADDR -method=github
    PUBLIC_KEY=$(vault read -address=$VAULT_ADDR -field=public $VAULT_PATH)
    PRIVATE_KEY=$(vault read -address=$VAULT_ADDR -field=private $VAULT_PATH)
    docker run --rm -v hint_config:/data busybox sh -c \
        "mkdir /data/token_key && echo $PUBLIC_KEY | base64 -d >/data/token_key/public_key.der && echo $PRIVATE_KEY | base64 -d >/data/token_key/private_key.der"
}

tar -xvf $1 -C $RESTORE_WORKING_DIR
md5sum --check $RESTORE_WORKING_DIR/checklist.chk
assert_all_data_exists $RESTORE_WORKING_DIR
restore $RESTORE_WORKING_DIR
if [ -f "$RESTORE_WORKING_DIR/cipher_path" ]; then
    echo "Do you want to restore cipher keys from vault?"
    read -p "Restore keys? y/n" -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        restore_key
    fi
fi

echo "Restore complete"
rm -rf $RESTORE_WORKING_DIR
