proxy:
  host: naomi-dev.dide.ic.ac.uk
  port_http: 80
  port_https: 443
  ssl:
    certificate: VAULT:secret/hint/ssl/dev:certificate
    key: VAULT:secret/hint/ssl/dev:key

vault:
  addr: https://vault.dide.ic.ac.uk:8200
  auth:
    method: approle
    args:
      role_id: $VAULT_AUTH_ROLE_ID
      secret_id: $VAULT_AUTH_SECRET_ID

hint:
  issue_report_url: VAULT:secret/hint/flow-webhooks/issue-report:url
  email:
    password: VAULT:secret/hint/email:password

hintr:
  use_mock_model: true
