volumes:
    db:
      name: "hint_db_data"
      path: "/pgdata"
    redis:
      name: "hint_redis_data"
      path: "/data"
    config:
      name: "hint_config"
      path: "/etc/hint"
    uploads:
      name: "hint_uploads"
      path: "/uploads"
    results:
      name: "hint_results"
      path: "/results"

redis:
  tag: "5.0"
  volumes:
    - "redis"

db:
  tag: "master"
  volumes:
    - "db"

hint:
  tag: "master"
  volumes:
    - "uploads"
    - "config"
    - "results"
  expose: true

hintr-loadbalancer:
  tag: "main"
  api_instances: 1

hintr:
  tag: "master"
  port: 8888
  workers: 2
  calibrate-workers: 1
  volumes:
    - "uploads"
    - "results"
  use_mock_model: false

proxy:
  host: localhost
  # port_http: 80
  # port_https: 443

docker:
  network: hint_nw
  default_tag: master
  prefix: hint

users:
  add_test_user: true
