redis:
  tag: "5.0"
  volume: "hint_redis_data"

db:
  tag: master
  volume: "hint_db_data"

hint:
  tag: "master"
  volumes:
    uploads: "hint_uploads"
    config: "hint_config"
  expose: true

hintr:
  tag: "master"
  workers: 2
  calibrate_workers: 1
  volumes:
    results: "hint_results"
    prerun: "hint_prerun"
  use_mock_model: false

proxy:
  tag: "mrc-3592"
  host: localhost
  # port_http: 80
  # port_https: 443

docker:
  network: hint_nw
  default_tag: master
  prefix: hint

users:
  add_test_user: true
