redis:
  tag: "5.0"

db:
  tag: master
  volume: "hint_db_data"

hint:
  tag: "master"
  volumes:
    uploads: "hint_uploads"
    config: "hint_config"
  expose: true
  use_mock_model: false

hintr:
  tag: "master"
  workers: 2
  volumes:
    results: "hint_results"

proxy:
  host: localhost
  # port_http: 80
  # port_https: 443

docker:
  network: hint_nw
  default_tag: master
  prefix: hint

users:
  add_test_user: true
