redis:
  tag: "5.0"

db:
  tag: master
  volume: "hint_db_data"

hint:
  tag: "master"
  volume: "hint_uploads"
  expose: true

hintr:
  tag: "master"

proxy:
  host: localhost
  # port_http: 80
  # port_https: 443

docker:
  network: hint_nw
  default_tag: master
  prefix: hint

users:
  add_test_user: true
