proxy:
  host: naomi-preview.dide.ic.ac.uk
  port_http: 80
  port_https: 443
  ssl:
    certificate: VAULT:secret/hint/ssl/preview:certificate
    key: VAULT:secret/hint/ssl/preview:key

vault:
  addr: https://vault.dide.ic.ac.uk:8200
  auth:
    method: approle
    args:
      role_id: $VAULT_AUTH_ROLE_ID
      secret_id: $VAULT_AUTH_SECRET_ID

hint:
  issue_report_url: VAULT:secret/hint/flow-webhooks/issue-report:url
  oauth2_client_adr_url: http://hint_resource_server:5000 
  oauth2_login_method: true
  oauth2_client_id: VAULT:secret/hint/oauth2/development:id
  oauth2_client_secret: VAULT:secret/hint/oauth2/development:secret
  oauth2_client_url: VAULT:secret/hint/oauth2/development:url
  oauth2_client_audience: naomi
  email:
    password: VAULT:secret/hint/email:password
