hint:
  adr_url: https://adr.unaids.org/
  issue_report_url: VAULT:secret/hint/flow-webhooks/issue-report:url
  oauth2_client_id: VAULT:secret/hint/oauth2/auth0:id
  oauth2_client_secret: VAULT:secret/hint/oauth2/auth0:secret
  oauth2_client_url: VAULT:secret/hint/oauth2/auth0:url
  email:
    password: VAULT:secret/hint/email:password

hintr:
  workers: 5
  calibrate_workers: 2 

proxy:
  host: wpia-naomi.dide.ic.ac.uk
  port_http: 80
  port_https: 443

vault:
  addr: https://vault.dide.ic.ac.uk:8200
  auth:
    method: github

users:
  add_test_user: false

deploy:
  protect_data: true
