hint:
  adr_url: https://adr.unaids.org/
  issue_report_url: VAULT:secret/hint/flow-webhooks/issue-report:url
  oauth2_login_method: false
  email:
    password: VAULT:secret/hint/email:password

hintr:
  workers: 5
  calibrate_workers: 2 

proxy:
  host: naomi.unaids.org
  port_http: 80
  port_https: 443
  ssl:
    certificate: VAULT:secret/hint/ssl/unaids:certificate
    key: VAULT:secret/hint/ssl/unaids:key

vault:
  addr: https://vault.dide.ic.ac.uk:8200
  auth:
    method: github

users:
  add_test_user: false

deploy:
  protect_data: true
