proxy:
  host: naomi-staging.dide.ic.ac.uk
  port_http: 80
  port_https: 443
  ssl:
    certificate: VAULT:secret/hint/ssl/staging:certificate
    key: VAULT:secret/hint/ssl/staging:key

vault:
  addr: https://vault.dide.ic.ac.uk:8200
  auth:
    method: approle
    args:
      role_id: $VAULT_AUTH_ROLE_ID
      secret_id: $VAULT_AUTH_SECRET_ID

hint:
  issue_report_url: VAULT:secret/hint/flow-webhooks/issue-report:url
  oauth2_client_id: VAULT:secret/hint/oauth2/auth0:id
  oauth2_client_secret: VAULT:secret/hint/oauth2/auth0:secret
  oauth2_client_url: VAULT:secret/hint/oauth2/auth0:url
  oauth2_login_method: false
  email:
    password: VAULT:secret/hint/email:password
